/**
 * Writes the recordings the pyEDFlib cross-check reads.
 *
 * These are separate from `test/fixtures/generate.mjs` and have a different job. Those
 * fixtures target specific things real files do wrong, several of which pyEDFlib refuses
 * to open at all — a truncated file, a header whose digital range is a single point. What
 * is wanted here is the opposite: ordinary, well-formed recordings across a wide spread of
 * calibrations, so that two implementations can be asked for the same numbers.
 *
 * The seed is fixed, so a mismatch reported on one machine reproduces on another.
 */

import { mkdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildTal, writeEdf } from '../fixtures/edf-writer.mjs';

export const OUT_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'generated');

/** Deterministic, so a failure names a file that can be regenerated byte for byte. */
function random(seed) {
  let state = seed;
  return () => (state = (state * 1103515245 + 12345) % 2147483648) / 2147483648;
}

export function generate(seed = 7, count = 80) {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const rnd = random(seed);
  const pick = (values) => values[Math.floor(rnd() * values.length)];
  const int = (lo, hi) => lo + Math.floor(rnd() * (hi - lo + 1));

  // Spans chosen to cover the ranges real hardware declares, plus the extremes of what the
  // 8-character header fields can hold. The gain is (physMax - physMin) / (digMax - digMin),
  // so pairing these gives gains from about 1e-9 to about 1e5.
  const digitalMins = [-32768, -8192, -2048, -1000, -100, -1];
  const digitalMaxes = [32767, 8191, 2047, 1000, 100, 1];
  const physicalMins = [-250, -100, -5, -1, -0.5, -99999, -0.0001, 0, 34];
  const physicalMaxes = [250, 100, 5, 1, 0.5, 99999, 0.0001, 40];

  const written = [];
  for (let i = 0; i < count; i++) {
    const digMin = pick(digitalMins);
    const digMax = pick(digitalMaxes);
    const physMin = pick(physicalMins);
    const physMax = pick(physicalMaxes);
    if (digMax <= digMin || physMax <= physMin) continue;

    const samplesPerRecord = pick([1, 3, 7, 16, 64, 256]);

    /*
      Every fourth recording is BDF, where a sample is three bytes rather than two.

      The 24-bit path is where a reader is most likely to be quietly wrong: the sign has to
      be extended by hand, and a value that comes out unsigned is not obviously wrong on
      inspection — it is a large positive number where a large negative one belongs. The
      digital range is BioSemi's own, so the extremes exercise both ends of it.
    */
    const bdf = i % 4 === 3;
    const recordDuration = pick([1, 2, 0.5]);
    const name = `x${String(i).padStart(3, '0')}.${bdf ? 'bdf' : 'edf'}`;

    /*
      Both endpoints of the digital range appear in every recording, deliberately.

      digitalMin and digitalMax are the two points the header actually calibrates, so they
      are where a mapping derived a slightly different way shows the largest disagreement.
      Interior codes and a random sample fill in the rest.
    */
    const low = bdf ? -8388608 : digMin;
    const high = bdf ? 8388607 : digMax;
    const codes = [low, high, 0, low + 1, high - 1, Math.round((low + high) / 2)];

    // Half the recordings carry EDF+/BDF+ events, so the annotation reader is compared too.
    const annotated = i % 2 === 0;
    const events = [
      { onset: 0.25, duration: null, text: 'no duration' },
      { onset: 0.5, duration: 1.5, text: 'with duration' },
      { onset: 1, duration: 0, text: 'zero duration' },
    ];

    writeEdf({
      path: path.join(OUT_DIR, name),
      bdf,
      reserved: bdf ? (annotated ? 'BDF+C' : '24BIT') : annotated ? 'EDF+C' : '',
      numRecords: int(1, 5),
      recordDuration,
      /*
        EDF+ specifies the identification fields, and pyEDFlib enforces them: it refuses a
        file marked EDF+C whose recording field does not open with a Startdate matching the
        header's own date. That strictness is the reason it is worth comparing against, so
        the generated files meet it rather than working around it.
      */
      ...(annotated
        ? {
            startDate: '02.03.02',
            startTime: '22.15.00',
            patient: 'X F 02-MAY-1951 X',
            recording: 'Startdate 02-MAR-2002 X X X',
          }
        : {}),
      // A record's timekeeping TAL states where that record starts, which is its index
      // times the record duration — not its index. Writing the index made every recording
      // whose records are not one second long internally inconsistent, and pyEDFlib
      // rejected exactly those outright rather than reading them wrongly.
      ...(annotated
        ? { talsForRecord: (record) => buildTal(record * recordDuration, record === 0 ? events : []) }
        : {}),
      signals: [
        {
          label: `sig${i}`,
          dimension: 'uV',
          physMin,
          physMax,
          digMin: low,
          digMax: high,
          samplesPerRecord,
          gen: (record, sample) => {
            const step = (record * samplesPerRecord + sample) % (codes.length + 1);
            return step < codes.length ? codes[step] : int(low, high);
          },
        },
        ...(annotated
          ? [{
              label: bdf ? 'BDF Annotations' : 'EDF Annotations',
              dimension: '',
              physMin: -1,
              physMax: 1,
              digMin: bdf ? -8388608 : -32768,
              digMax: bdf ? 8388607 : 32767,
              samplesPerRecord: 60,
              annotations: true,
            }]
          : []),
      ],
    });
    written.push(name);
  }
  return written;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const written = generate();
  process.stdout.write(`Wrote ${written.length} recordings to ${OUT_DIR}\n`);
}
